### ISSUE TITLE
I think I can fix your problem

### ISSUE THREAD

**Issue by JamCh01** [ghetzel/webfriend#2]
https://github.com/ghetzel/webfriend/blob/master/webfriend/rpc/dom.py#L627

I meet the same problem as yours. And I got your code~
When I wanna give it up, I find if I use DOM.getDocument before DOM.performSearch, the DOM.getSearchResults works well!

here is my code, but I dont used your lib~
```python
from chromeremote import ChromeTab, TabTimeout
from time import sleep, time


def common(kwargs):
    current_tab = kwargs.get('current_tab')
    nodeIds = kwargs.get('nodeIds')
    for nodeId in nodeIds:
        print nodeId


def callret(kwargs):
    searchId = kwargs.get('searchId')
    current_tab = kwargs.get('current_tab')
    resultCount = kwargs.get('resultCount')
    current_tab.DOM.getSearchResults(
        searchId=searchId, fromIndex=0, toIndex=resultCount, callback=common)


def main():
    tab = ChromeTab('127.0.0.1', 9222)
    tab.open_tab()
    tab.Network.enable(
        maxTotalBufferSize=10000000, maxResourceBufferSize=5000000)
    tab.Page.enable()
    tab.DOM.enable()
    tab.Overlay.enable()
    tab.CSS.enable()
    tab.Page.navigate(url='https://segmentfault.com/')
    sleep(3)
    tab.DOM.getDocument()
    tab.DOM.performSearch(
        nodeId=0,
        query='python',
        includeUserAgentShadowDOM=False,
        callback=callret)
    try:
        for msg in tab.messages(timeout_return_none=True):
            if time() - tab.start_time > 5:
                break
            if msg is None:
                continue
            with open('log.txt', 'a') as f:
                f.write(str(msg) + '\n')
    except TabTimeout:
        pass


if __name__ == '__main__':
    main()
```

**Comment by ghetzel** [comment]
Hey!  Thanks so much for taking a look at this, this problem was bugging me.

I'll poke at this soon and see if I can fill in the `xpath()` implementation.

**Comment by JamCh01** [comment]
if you dont have enough time to fix this bug, I will pull request~

**Comment by JamCh01** [comment]
fighting!~

**Comment by JamCh01** [comment]
btw, we are building the same lib as yours, here -> [chromeremote](https://github.com/sadnoodles/chromeremote)

**Comment by ghetzel** [comment]
Best of luck!  This is definitely an interesting problem domain that needs good Python libraries.  Now that phantomjs is in the state it's in, I'm super happy to see so many projects working in this space.

**Comment by JamCh01** [comment]
Yep~  We use Chrome instead of PhantomJS. Good luck for you~
