### ISSUE TITLE
Spam Traffic from this repository

### ISSUE THREAD

**Issue by guiman87** [ghetzel/webfriend#8]
Hi there! I work for the site https://capplatam.com, something very strange is occurring, one of your repos (https://github.com/ghetzel/webfriend)  is referring a lot of strange traffic to my website, can you explain the reason?  
seems  to be spam traffic...

thanks!

**Comment by ghetzel** [comment]
Hello!

In all likelihood this is automated web crawling traffic from my former employer (PerfomLine https://performline.com).  They use this project to run an internal crawler as part of a regulatory compliance monitoring solution for their clients.  If you send an email to tech@performline.com, that should go to my old team and they can add your domain(s) to a blacklist.
